export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";
export const REVIEW_QUESTIONS_SUCCESS = "REVIEW_QUESTIONS_SUCCESS";
export const REVIEW_QUESTIONS_FAIL = "REVIEW_QUESTIONS_FAIL";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL";
export const SELECT_QUESTION = "SELECT_QUESTION";
export const RESET_REVIEW_QUESTIONS = "RESET_REVIEW_QUESTIONS";
export const GET_CREATED_QUIZZES_LIST = "GET_CREATED_QUIZZES_LIST";
export const GET_CREATED_QUIZZES_LIST_FAIL = "GET_CREATED_QUIZZES_LIST_FAIL";
export const GET_PRACTICE_QUIZZES_LIST = "GET_PRACTICE_QUIZZES_LIST";
export const GET_PRACTICE_QUIZZES_LIST_FAIL = "GET_PRACTICE_QUIZZES_LIST_FAIL";
export const GET_TAKEN_QUIZZES_LIST = "GET_TAKEN_QUIZZES_LIST";
export const GET_TAKEN_QUIZZES_LIST_FAIL = "GET_TAKEN_QUIZZES_LIST_FAIL";
export const GET_CREATED_QUIZ = "GET_CREATED_QUIZ";
export const GET_CREATED_QUIZ_FAIL = "GET_CREATED_QUIZ_FAIL";
export const GET_PRACTICE_QUIZ = "GET_PRACTICE_QUIZ";
export const GET_PRACTICE_QUIZ_FAIL = "GET_PRACTICE_QUIZ_FAIL";
export const GET_TAKEN_QUIZ = "GET_TAKEN_QUIZ";
export const GET_TAKEN_QUIZ_FAIL = "GET_TAKEN_QUIZ_FAIL";
export const RESET_SHOW_QUIZ = "RESET_SHOW_QUIZ";
export const TAKE_QUIZ = "TAKE_QUIZ";
export const TAKE_QUIZ_FAIL = "TAKE_QUIZ_FAIL";
export const RESET_TAKE_QUIZ = "RESET_TAKE_QUIZ";




